### PR TITLE
need arch after all

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/splipy-feedstock/issues/1

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forger When making this kind of change we need to "rerender" the feedstock. An easy way is to add this comment:

@conda-forge-admin please rerender

**Review by conda-forger — APPROVED** [review]

**Comment by conda-forger** [comment]
Thanks for the speedy help!

**Comment by izahn** [comment]
Sure! Next time wait for the [CI check](https://github.com/conda-forge/splipy-feedstock/pull/2/checks) to finish before you merge though!

**Comment by conda-forger** [comment]
Ok, I will do so ... just learning the ropes here.

**Comment by conda-forger** [comment]
11 of the 13 CI checks passed.  The remaining 2 show a `git fetch` failure, I'm not sure how to fix this.

**Comment by conda-forger** [comment]
@conda-forge/core please help

**Pull request merged**
